### PR TITLE
enter some simple descriptions for events (take 2)

### PR DESCRIPTION
**Pull request by nikomatsakis**
Ok, I accidentally pushed my previous PR, which I have since reverted, so let me try this again. Here are some simple descriptions for events. I do have a problem that `just build` will not run on my system. I get errors about `fd` not being present. I rewrote the script to use `find` but I still get a mysterious error I don't have time to track down:

```
error: Recipe `dhall-format` failed on line 17 with exit code 127
```

### CODE REVIEW

**Comment by nikomatsakis** [comment]
cc @cjosephson and @ggilmore -- any tips on the error I'm seeing? Also, are you ok with rewriting to use `find`?

**Comment by cjosephson** [comment]
Hmm, I don't get notified via email about these comment, so didn't see this until now.

The close paren is line 17:  
`  local FORMAT_ARGS=(
    "format"
    "--inplace"
    "${file}"
  )`
https://github.com/alumxi22/website/blob/master/scripts/dhall-format.sh

Sounds like error 127 happens when a command can't be found...what kind of environment do you have (OSX/linux/bash/zsh/etc)?

**Comment by nikomatsakis** [comment]
The problem seems to be that I lack the `format` command. What *is* this command? I guess @ggilmore you probably know ;)

**Comment by cjosephson** [comment]
> The problem seems to be that I lack the `format` command. What _is_ this command? I guess @ggilmore you probably know ;)

Does a version pop out if you type 'dhall' into your shell? @ggilmore suggested something might be wrong with the dhall installation

**Comment by ggilmore** [comment]
@nikomatsakis Do you have `dhall` installed on your machine?

Also, it's easier if you create a new branch off of this repository when submitting a PR instead of creating a fork. This allows the CI pipeline to run (I believe that you have write access).

**Comment by nikomatsakis** [comment]
@ggilmore hmm if the instructions suggested I installed it then probably, but maybe in some weird path I suppose.

**Comment by nikomatsakis** [comment]
@ggilmore I do have dhall installed, or at least when I run `dhall` from within the directory everything seems to work fine. But if I run `format` there is no such command. Is `format` something that comes with `dhall`?

**Comment by nikomatsakis** [comment]
OK, I opened #12 using a branch rather than coming from a fork

**Pull request closed without merging**
