### PR TITLE
xiohazard properly masked

### PR DESCRIPTION
**Pull request by WanderingStar**
There shouldn't be white inside the red ring.

### CODE REVIEW

**Review by cjosephson — CHANGES_REQUESTED** [review]
You need to do the deploy steps in the README before committing, or else the checks will all fail

**Comment by ggilmore** [comment]
@WanderingStar In addition, please merge in the latest commits from the base branch now that https://github.com/alumxi22/website/pull/15 has been merged. Thanks for the PR!

**Comment by WanderingStar** [comment]
Surprised that I need to have everything up and running to update a static asset. Got partway through the install and failed on some missing PGP keys. Will attempt to continue tomorrow.

**Comment by ggilmore** [comment]
@WanderingStar CI is set up to enforce that the built version of the site is consistent with what's committed in the `docs/` folder (which is what Github Pages is configured to look at, not anywhere else). So, changing one of the content files or static assets requires a rebuild of the site (which changes the output in the `docs` folder).

**Comment by WanderingStar** [comment]
Where is `just` supposed to have come from? I've gotten this far, but `zsh: command not found: just`

```
git clone git@github.com:alumxi22/website.git
cd website
git submodule update --init --recursive
brew install parallel
scripts/asdf-add-plugins.sh
brew install asdf
xcode-select --install
brew install asdf
scripts/asdf-add-plugins.sh
brew install gpg2
scripts/asdf-add-plugins.sh
asdf install
just install
```

**Comment by ggilmore** [comment]
@WanderingStar 

What is the output of `./scripts/asdf-add-plugins.sh`? 

That script adds that plugin: https://github.com/alumxi22/website/blob/f91dceb4e1f26ffb7471ede7248f8c3b11548129/scripts/asdf-add-plugins.sh#L18

That script is also the same one that CI uses:

https://github.com/alumxi22/website/blob/f91dceb4e1f26ffb7471ede7248f8c3b11548129/.github/workflows/ci.yaml#L12-L13

https://github.com/alumxi22/website/runs/1693216398#step:4:1

**Comment by WanderingStar** [comment]
```
aneel@Avernus website % scripts/asdf-add-plugins.sh
+ asdf plugin-add hugo https://github.com/beardix/asdf-hugo.git
Plugin named hugo already added
aneel@Avernus website % which just
just not found
```

**Comment by WanderingStar** [comment]
Ah, the script is stopping after determining that hugo was installed already.

**Comment by WanderingStar** [comment]
So, because I didn't have `gpg` installed, that script installed hugo and nodejs and then failed.

**Comment by ggilmore** [comment]
Yeah, it seems like the script must have failed earlier and I didn't realize that plugin-add returns a non-zero exit code if the plugin is already present (and `set -e` is specified). Sorry about that. You can just add the plugins individually though.

**Comment by WanderingStar** [comment]
Commented those two out and set -x:

```
aneel@Avernus website % scripts/asdf-add-plugins.sh
++ dirname scripts/asdf-add-plugins.sh
+ cd scripts/..
+ set -euxo pipefail
+ /Users/aneel/.asdf/plugins/nodejs/bin/import-release-team-keyring
gpg: key D7062848A1AB005C: "Beth Griggs <bgriggs@redhat.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 7434390BDBE9B9C5: "Colin Ihrig <cjihrig@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 92EF661D867B9DFA: "Danielle Adams <adamzdanielle@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key C97EC7A07EDE3FC1: "keybase.io/jasnell <jasnell@keybase.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 770F7A9A5AE15600: "Michaël Zasso (Targos) <targos@protonmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key E73BC641CC11F4C8: "Myles Borins <myles.borins@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key C43CEC45C17AB93C: "Richard Lau <rlau@redhat.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key C273792F7D83545D: "Rod Vagg <rod@vagg.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key F07496B3EB3C1762: "Ruben Bridgewater <ruben@bridgewater.de>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 97B01419BD92F80A: "Ruy Adorno <ruyadorno@hotmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key F13993A75599653C: "Shelley Vohr (security is major key) <shelley.vohr@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ OTHER_PACKAGES=("yarn" "dhall" "shellcheck" "shfmt" "fd" "just")
+ for package in '"${OTHER_PACKAGES[@]}"'
+ asdf plugin-add yarn
+ for package in '"${OTHER_PACKAGES[@]}"'
+ asdf plugin-add dhall
+ for package in '"${OTHER_PACKAGES[@]}"'
+ asdf plugin-add shellcheck
+ for package in '"${OTHER_PACKAGES[@]}"'
+ asdf plugin-add shfmt
+ for package in '"${OTHER_PACKAGES[@]}"'
+ asdf plugin-add fd
+ for package in '"${OTHER_PACKAGES[@]}"'
+ asdf plugin-add just
aneel@Avernus website % which just
just not found
```

**Comment by WanderingStar** [comment]
Something wrong with my path?
```
aneel@Avernus website % echo $PATH
/Users/aneel/.asdf/shims:/usr/local/opt/asdf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
```

**Comment by WanderingStar** [comment]
Ah, needed to rerun `asdf install`

**Comment by ggilmore** [comment]
@WanderingStar

Did you `asdf install` afterwards?

**Comment by WanderingStar** [comment]
```
aneel@Avernus website % just all
./scripts/dhall-format.sh
./scripts/dhall-format.sh: line 8: mapfile: command not found
```
`mapfile` was introduced in Bash 4

```
aneel@Avernus website % bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by WanderingStar** [comment]
```
brew install bash
export PATH=/usr/local/bin:$PATH
bash --version
```

```
aneel@Avernus website % bash --version
GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin19.6.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
aneel@Avernus website % just
./scripts/dhall-format.sh
error: Recipe `dhall-format` failed on line 19 with exit code 255
```

**Comment by ggilmore** [comment]
@WanderingStar Would you mind upgrading your bash with homebrew (e.g. `brew install bash`)? I can add it to the readme. Honestly, upgrading bash is one of the first things that I do on a new mac since Apple ship anything past v3 due to GPL V3.

**Comment by ggilmore** [comment]
Oh, I see that you did that already. Could you try doing two things:

1) Setting `-x` in the dhall format script
2) What does `/usr/bin/env bash` point to for you? What is it's bash version?

**Comment by WanderingStar** [comment]
```
aneel@Avernus website % /usr/bin/env bash --version
GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin19.6.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
aneel@Avernus website % just
./scripts/dhall-format.sh
++ dirname ./scripts/dhall-format.sh
+ cd ./scripts/..
+ set -eu pipefail
+ DHALL_FILES=()
+ mapfile -t DHALL_FILES
++ fd --extension dhall
+ export -f format
+ echo 'will cite'
+ parallel --citation
+ ./scripts/parallel_run.sh format '{}' ::: scripts/ci/dhall/imports.dhall scripts/ci/dhall/jobs/check-docs-up-to-date.dhall scripts/ci/dhall/jobs/check-rendered-pipeline-up-to-date.dhall scripts/ci/dhall/jobs/dhall-format.dhall scripts/ci/dhall/jobs/dhall-lint.dhall scripts/ci/dhall/jobs/prettier.dhall scripts/ci/dhall/jobs/shellcheck.dhall scripts/ci/dhall/jobs/shfmt.dhall scripts/ci/dhall/setup.dhall scripts/ci/dhall/workflow.dhall
scripts/ci/dhall/imports.dhall:

Warning: When trying to create:

↳ /Users/aneel/.cache/dhall

... the following exception was thrown:

↳ /Users/aneel/.cache/dhall: createDirectory: already exists (File exists)


Warning: Could not get or create the default cache directory:

↳ /Users/aneel/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.

scripts/ci/dhall/jobs/check-docs-up-to-date.dhall:

Warning: When trying to create:

↳ /Users/aneel/.cache/dhall

... the following exception was thrown:

↳ /Users/aneel/.cache/dhall: createDirectory: already exists (File exists)


Warning: Could not get or create the default cache directory:

↳ /Users/aneel/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.

scripts/ci/dhall/jobs/check-rendered-pipeline-up-to-date.dhall:

Warning: When trying to create:

↳ /Users/aneel/.cache/dhall

... the following exception was thrown:

↳ /Users/aneel/.cache/dhall: createDirectory: already exists (File exists)


Warning: Could not get or create the default cache directory:

↳ /Users/aneel/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.

scripts/ci/dhall/jobs/dhall-format.dhall:

Warning: When trying to create:

↳ /Users/aneel/.cache/dhall

... the following exception was thrown:

↳ /Users/aneel/.cache/dhall: createDirectory: already exists (File exists)


Warning: Could not get or create the default cache directory:

↳ /Users/aneel/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.

scripts/ci/dhall/jobs/dhall-lint.dhall:

Warning: When trying to create:

↳ /Users/aneel/.cache/dhall

... the following exception was thrown:

↳ /Users/aneel/.cache/dhall: createDirectory: already exists (File exists)


Warning: Could not get or create the default cache directory:

↳ /Users/aneel/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.

scripts/ci/dhall/jobs/prettier.dhall:

Warning: When trying to create:

↳ /Users/aneel/.cache/dhall

... the following exception was thrown:

↳ /Users/aneel/.cache/dhall: createDirectory: already exists (File exists)


Warning: Could not get or create the default cache directory:

↳ /Users/aneel/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.

scripts/ci/dhall/jobs/shfmt.dhall:

Warning: When trying to create:

↳ /Users/aneel/.cache/dhall

... the following exception was thrown:

↳ /Users/aneel/.cache/dhall: createDirectory: already exists (File exists)


Warning: Could not get or create the default cache directory:

↳ /Users/aneel/.cache/dhall

You can enable caching by creating it if needed and setting read,
write and search permissions on it or providing another cache base
directory by setting the $XDG_CACHE_HOME environment variable.

yarn run prettier
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.63.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
error: Recipe `prettier` was terminated on line 16 by signal 6
```

But I don't have icu4c 63, I have 64.

```
aneel@Avernus website % brew upgrade icu4c
...
==> Upgrading 1 outdated package:
icu4c 64.2 -> 67.1
==> Upgrading icu4c 64.2 -> 67.1
...
aneel@Avernus website % just
yarn run v1.22.2
$ prettier '**/{*.{js?(on),ts?(x),graphql,md,scss,toml},.*.js?(on)}' --write --list-different
✨  Done in 0.82s.
```
🚀

**Comment by ggilmore** [comment]
@WanderingStar Did you not install nodejs on your machine before?

**Comment by WanderingStar** [comment]
No, I don't use node, generally speaking, and try to keep things like that in containers, generally. I would have done that for this, but it was going to be such a small change! One leeeetle png!

**Comment by ggilmore** [comment]
Hmm, I'm not sure what the issue is then. I know that the asdf-nodejs plugin is tested on mac: https://travis-ci.org/github/asdf-vm/asdf-nodejs/jobs/752990746, but I don't know why it would be failing in this case...

**Comment by ggilmore** [comment]
I also test my asdf-plugins that I wrote using this same scheme (relying on asdf-nodejs for tests) on mac and don't see issues there: https://github.com/ggilmore/asdf-just/pull/5/checks?check_run_id=1699681173

**Review by ggilmore — APPROVED** [review]

**Pull request merged**
